name: 新镜像请求
description: 在 SJTUG 软件源镜像服务中添加新的镜像源 / Request new mirror
title: "[Mirror Request]: "
labels: [new-mirror]
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        欢迎您向 SJTUG 软件源镜像服务提交新的镜像请求。请您填写这个表单，以帮助维护者更好地了解软件源相关信息。
  - type: input
    id: name
    attributes:
      label: 软件源名称
      description: 软件源名称将成为该软件源在 SJTUG 镜像服务中的网址的一部分。
      placeholder: e.g. Debian
    validations:
      required: true
  - type: textarea
    id: upstream
    attributes:
      label: 上游路径
      description: 通常为 rsync 地址。
    validations:
      required: false
  - type: markdown
    id: optional_info
    attributes:
      value: |
        以下内容选填。填写下面的内容可以帮助镜像源维护者更好地决定是否可以镜像。
  - type: textarea
    id: other_mirrors
    attributes:
      label: 国内其他镜像源同步情况
      description: 您可以在 https://github.com/tuna/issues 和 https://github.com/ustclug/mirrorrequest 搜索相关的请求。
    validations:
      required: false
  - type: textarea
    id: sync_method
    attributes:
      label: 同步方法
      description: 通常为 rsync 地址、镜像工具、或上游推荐的镜像方法。
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: 这个镜像源从未在 https://github.com/sjtug/mirror-requests/issues 讨论过，也没有在 https://mirror.sjtu.edu.cn 上线。
      description: 请不要提交重复的请求。
      options:
        - label: 我已确认
          required: true
